# Author: Bucky Frost
# File: Makefile
# Purpose: Makefile for homework 3 CS 372.

CC = g++
CFLAGS =  -std=c++11
CFLAGS_DEBUG = -Wall -g -pg
SRC = numerals.cpp
INCLUDE = -I ./Catch/single_include/

all:
	$(CC) $(CFLAGS) $(INCLUDE) $(SRC)  -o ./build/numerals.out
